app:
  version: @MVN@project.version@MVN@
  name: @MVN@project.name@MVN@
  description: @MVN@project.description@MVN@

spring:
  application.name: laboratory-work
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db_user
    username: username
    password: password
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate:
      format_sql: true
  sql.init.mode: always
  flyway.enabled: true
  mvc:
    servlet:
      path: /user-api

server:
  servlet:
    context-path: ''
  api:
    version:
      users: v1
      auth: v1
      admin: v1
  repository:
    max-amount-on-all-getting: 1000
  port: 8080

cache:
  manager:
    expire-time:
      seconds: 30

auth:
  jwt:
    secret: woiet2^312o-kukkto43o2312o-!^&^%&!kukkt[k[k-y-05yi9hrfnoih^%&eheh
    lifetime: 300m

author:
  username: oneune
  email: babnicshev.back@mail.ru
  personal:
      first-name: Igor
      last-name: Babnischev
      middle-name: Vladimirovich
  addition:
    university:
      group: B20-603
